name: Selenium Daily Run

on:
  workflow_dispatch:  # Enables manual triggering of the workflow
  schedule:
    # Runs daily at 06:00 UTC
    - cron: '0 6 * * *'

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [dev, staging, production] # Run tests for each environment in parallel
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Allure
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -sLo allure.tgz https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz
          tar -xzvf allure.tgz -C /opt/
          sudo ln -sf /opt/allure-2.32.0/bin/allure /usr/local/bin/allure
          echo "Verifying Allure installation..."
          /usr/local/bin/allure --version

      # Run Selenium tests for the specified environment
      - name: Run tests for ${{ matrix.env_name }}
        env:
          TEST_ENV: ${{ matrix.env_name }}
        run: |
          echo "Running tests in $TEST_ENV"
          case "$TEST_ENV" in
            "dev") BASE_URL="https://user.dev-ooro.co.uk/" ;;
            "staging") BASE_URL="https://user.staging-ooro.co.uk/" ;;
            "production") BASE_URL="https://user.ooro.co.uk/" ;;
          esac
          echo "Using BASE_URL: $BASE_URL"
          TEST_RESULTS="test-output/results_${TEST_ENV}.xml"
          ALLURE_RESULTS="test-output/allure-results/${TEST_ENV}"
          pytest tests/ --junitxml="${TEST_RESULTS}" --alluredir="${ALLURE_RESULTS}" || true

      # Generate Allure Report for the respective environment
      - name: Generate Allure Report for ${{ matrix.env_name }}
        run: |
          allure generate test-output/allure-results/${{ matrix.env_name }} -o test-output/allure-report-${{ matrix.env_name }} --clean || true

      # Rename Allure report index.html
      - name: Rename Allure Report for ${{ matrix.env_name }}
        run: |
          mv test-output/allure-report-${{ matrix.env_name }}/index.html test-output/allure-report-${{ matrix.env_name }}/allure-report-${{ matrix.env_name }}.html

      # Upload Allure report artifacts for the respective environment
      - name: Upload Allure Report for ${{ matrix.env_name }}
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{ matrix.env_name }}
          path: test-output/allure-report-${{ matrix.env_name }}


  # Consolidate and send reports to Slack after all tests complete
  send-reports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: [ dev, staging, production ] # Run tests for each environment in parallel
    needs: selenium-test  # Wait for all selenium-test jobs to complete
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Download all reports
      - name: Download Allure Reports
        uses: actions/download-artifact@v3
        with:
          name: allure-report-dev
          path: test-output/allure-report-dev
      - uses: actions/download-artifact@v3
        with:
          name: allure-report-staging
          path: test-output/allure-report-staging
      - uses: actions/download-artifact@v3
        with:
          name: allure-report-production
          path: test-output/allure-report-production

      # Verify Allure Report for the respective environment
      - name: Verify Allure Report for ${{ matrix.env_name }}
        run: |
          if [ ! -f test-output/allure-report-${{ matrix.env_name }}/allure-report-${{ matrix.env_name }}.html ]; then
            echo "Allure report for ${{ matrix.env_name }} not found!" && exit 1
          else
            echo "Allure report for ${{ matrix.env_name }} exists."
          fi

      # Send Allure reports to Slack
      - name: Send Allure Reports to Slack
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_type: 'html'
          file_path: |
            test-output/allure-report-dev/allure-report-dev.html
            test-output/allure-report-staging/allure-report-staging.html
            test-output/allure-report-production/allure-report-production.html
          file_name: |
            allure-report-dev.html
            allure-report-staging.html
            allure-report-production.html
          initial_comment: 'Automation Testing Status: Reports for all environments'

